logging.file.name=myapplication.log

# DataSource settings: set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/TimeStamps
spring.datasource.username=flibustier
spring.datasource.password=root

# SQL logging
# spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate=ERROR
